services:
  - type: web
    name: ocr-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    buildFilter:
      paths:
      - requirements.txt
      - app.py
      - ocr_service.py
    plan: free
